name: Renovate

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6.0.2

      - uses: renovatebot/github-action@v46.1.10
        with:
          token: ${{ steps.token.outputs.token }}
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
